### ISSUE TITLE
netbios: disabled adapters

### ISSUE THREAD

**Issue by NEllis280** [dsccommunity/NetworkingDsc#434]
#### Details of the scenario you tried and the problem that is occurring
Disabling netbios generates an error if the adapter is disabled.  Test-DSCConfiguration determines the status appropriately, but Start-DSCConfiguration errors out when the adapter is disabled. 
#### Verbose logs showing the problem
From output when running start-dscConfiguration
PowerShell DSC resource MSFT_NetBios  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: An error result 
of '84' was returned when attemting to set NetBIOS configuration to 'Disable'. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

From Event Log:
Log Name:      Microsoft-Windows-DSC/Operational
Source:        Microsoft-Windows-DSC
Date:          12/13/2019 12:13:57 PM
Event ID:      4250
Task Category: None
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      Obfuscated.contoso.com
Description:
Job {16931954-1DE5-11EA-80D1-00155D741A0B} : 
Message System.InvalidOperationException: An error result of '84' was returned when attemting to set NetBIOS configuration to 'Disable'. 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Test
{
    [CmdletBinding()]
    Import-DSCResource -ModuleName NetworkingDsc -ModuleVersion 7.4.0.0

    NetBios Test
    {
        InterfaceAlias = 'SampleAlias'
        Setting        = 'Disable'
    }
}
```

#### The operating system the target node is running
Server 2012 R2 Datacenter 64-bit
WindowsBuildLabEx: 9600.19538.amd64fre.winblue_ltsb_escrow.191014-1700
OsLanguage:             en-US
OsMuiLanguages:     {en-US}

#### Version and build of PowerShell the target node is running
Powershell 5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
ModuleVersion 7.4.0.0

**Comment by NEllis280** [comment]
We did some more testing and it appears that the issue stems from the adapter not having an IP, rather than a simple enabled/disabled state.

**Comment by PlagueHO** [comment]
Hi @NEllis280 - sorry about the delay in looking into this. Do you mean that if the adapter does not have an IP address assigned then disabling the NetBios fails with the error shown?

**Comment by NEllis280** [comment]
That's correct.

**Comment by SDedik** [comment]
Just stumbled upon this issue in my environment. It pleases me that PR for this has already been submitted and the process is active. Looking forward to see a new version of the module!
